### ISSUE TITLE
Search box in top right corner won't display text or cursor

### ISSUE THREAD

**Issue by jsi** [enonic/site-developer#126] opened 2019-02-05 11:44 UTC
**Steps to reproduce:**
1. Go to the developer portal in Safari on Mac
2. Click the Magnifier glass in the the top right corner
3. Starting typing in the area that appears.

**What happens:**
 - a waiting splash appears briefly for every letter, so it appears as if a search is done with what is typed, but the text is just white and what has been typed is not visible:
<img width="414" alt="screenshot 2019-02-05 12 42 36" src="https://user-images.githubusercontent.com/477453/52271370-bce23600-2943-11e9-90fa-b1ec961de27c.png">

**What is expected:**
- The typed text should appear and search results should be displayed below.

**Comment by jsi** [comment] 2019-02-05 13:59
**Update:** Turns out search works.  If what is typed actually match the search, the search result appears, even if the typed text is not visible:
![screenshot 2019-02-05 14 58 39](https://user-images.githubusercontent.com/477453/52278153-a7c2d280-2956-11e9-8b80-78b04c508387.png)

**Comment by hjelmevold** [comment] 2019-05-07 11:54
Duplicate of #139

**Closed by hjelmevold** 2019-05-07 11:54 UTC
Labels: bug
